### PR TITLE
Modifications to README

### PR DESCRIPTION
**Pull request by Suharsh329**

### CODE REVIEW

**Comment by tonsky** [comment]
I’d like to keep “absolute necessary minimum of”, at least in some form

**Comment by tonsky** [comment]
Also, what’s wrong with the word “booleans” (meaning constants `true`/`false`)?

**Comment by Suharsh329** [comment]
You are entitled to writing it in your style, but I think that “absolute
necessary minimum of” is too much just to say a small amount, minimal or
nominal. It's usually taken into consideration when using minimal that it
is necessary or of importance.
Regarding "booleans", the term is boolean, having the value either true or
false. You may use "boolean values" if you'd like, otherwise the
word/keyword is Boolean/boolean.

**Comment by tonsky** [comment]
> It's usually taken into consideration when using minimal that it is necessary or of importance.

I think you’re right. Thanks!

**Pull request merged**
